services:
  - type: web
    name: app
    env: docker
    region: frankfurt
    plan: starter
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
            name: appdb
            property: connectionString
      - fromGroup: app-settings

databases:
  - name: appdb
    region: frankfurt
    plan: free

envVarGroups:
  - name: app-settings
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
